title: Piyush Taneja # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <label style="font-weight: bold; font-size: large;">Product Manager</label>
  <br><br>
  <img style="max-width: 6%;" src="/images/education_thumbnail.png"> MBA <a href="http://www.iimu.ac.in/" target="_blank" style="cursor:pointer"><label style="cursor: pointer">IIM Udaipur</label></a> 
  <br><br>
    <a href="mailto:piyushtaneja.taneja@gmail.com"><img style="max-width: 6%; vertical-align:middle;" src="/images/mail_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">Contact Me</label></a>
  <br><br> 
   <a href="/Piyush_Taneja_Resume.pdf" style="cursor:pointer" target="_blank"><img style="max-width: 6%; vertical-align:middle;" src="/images/resume_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">Resume</label></a>
  <br><br>
    <a href="https://www.linkedin.com/in/piyush-taneja/" target="_blank" style="cursor:pointer"><img style="max-width: 6%; vertical-align: text-top" src="/images/linkedin_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">LinkedIn</label></a> 
  <br><br>
  <a href="https://github.com/piyush-taneja" target="_blank" style="cursor:pointer"><img style="max-width: 6%; vertical-align: text-top" src="/images/github.png"><label style="padding-left: 2%; cursor: pointer">Github</label></a> 
  <br><br> 
    <a href="https://www.hackerrank.com/piyush_taneja" target="_blank" style="cursor:pointer"><img style="max-width: 6%; vertical-align: text-top" src="/images/hackerrank.png"><label style="padding-left: 2%; cursor: pointer">Hackerrank</label></a> 
  <br><br>
  <a href="https://medium.com/@piyush_taneja" target="_blank" style="cursor:pointer"><img style="max-width: 6%; vertical-align: text-top" src="/images/medium_thumbnail.png"><label style="padding-left: 2%; cursor: pointer">Medium</label></a> 
  <br><br>


  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
